import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
padding = { x = 5, y = 5 }

[font]
size = 15.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

