[theme]
background = "default"
primary = "#D8DEE9"
secondary = "#DCDCDC"
title = "#88C0D0"
playing = "#2E3440"
playing_selected = "#A3BE8C"
playing_bg = "#5E81AC"
highlight = "#EBCB8B"
highlight_bg = "#81A1C1"
error = "#D8DEE9"
error_bg = "#BF616A"
statusbar = "#88C0D0"
statusbar_progress = "#5E81AC"
statusbar_bg = "default"
cmdline = "#D8DEE9"
cmdline_bg = "#434C5E"
search_match = "#A3BE8C"
